version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always

  db:
    build: 
      context: .
      dockerfile: pg.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=short_urls

    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local
